version: '3.8'

services:
  db:
    image: postgres:16-alpine3.18
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sccs
