version: '3.8'

services:
  db:
    image: postgres:16-alpine3.18
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sccs

  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sccs
      SPRING_DATASOURCE_USERNAME: db_admin
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
