spring:
  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://ep-weathered-math-909876.us-east-2.aws.neon.tech/sccs
    username: ssoslickk
    password: H94xCKgdQjuS
#    url: jdbc:postgresql://localhost:5432/sccs_db
#    username: sccs_user
#    password: sccspass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt_secret: aisderhoo
