spring:
  datasource:
    url: jdbc:postgresql://ep-weathered-math-909876.us-east-2.aws.neon.tech/sccs
    username: ssoslickk
    password: H94xCKgdQjuS
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect