spring:
  datasource:
#    url: jdbc:postgresql://ep-weathered-math-909876.us-east-2.aws.neon.tech/apartmentsdb
#    username: ssoslickk
#    password: H94xCKgdQjuS
  url: jdbc:postgresql://127.0.0.1:5432/sccs
  username: db_admin
  password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format-sql: true
